# Generated by Django 5.1.7 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_assetaddition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetaddition",
            name="asset_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
